/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parametre;

import metier.VIP;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import vue.MonModele;

/**
 *
 * @author Vincent
 */
public final class Appli extends javax.swing.JFrame {

    public static java.sql.Connection conn;

    /**
     * Creates new form Appli
     * @throws java.lang.Exception
     */
    public Appli() throws Exception {
        vVIP = new java.util.ArrayList<>();
        initComponents();

        // Les 3 prochaines lignes permettent de mettre l'application en plein écran
        this.pack();
        setDefaultLookAndFeelDecorated(true);
        this.setExtendedState(MAXIMIZED_BOTH);
        monModele = (MonModele) table.getModel();
        lireLesVIP();
        setLocation(250, 150);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        boutonMenuModifierVIP = new javax.swing.JMenu();
        boutonMenuAjouterVIP = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        boutonMenuModifierMariage = new javax.swing.JMenuItem();
        boutonMenuAjouterDivorce = new javax.swing.JMenuItem();
        boutonMenuAjouterPhoto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        boutonMenuAide = new javax.swing.JMenuItem();
        boutonMenuAPropos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Voicela");

        table.setModel(new MonModele(vVIP));
        jScrollPane1.setViewportView(table);

        boutonMenuModifierVIP.setText("File");
        boutonMenuModifierVIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonMenuModifierVIPActionPerformed(evt);
            }
        });

        boutonMenuAjouterVIP.setText("Ajouter un VIP");
        boutonMenuAjouterVIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutVIP(evt);
            }
        });
        boutonMenuModifierVIP.add(boutonMenuAjouterVIP);

        jMenuItem1.setText("Modifier un VIP");
        boutonMenuModifierVIP.add(jMenuItem1);

        boutonMenuModifierMariage.setText("Ajouter mariage");
        boutonMenuModifierMariage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonMenuModifierMariageActionPerformed(evt);
            }
        });
        boutonMenuModifierVIP.add(boutonMenuModifierMariage);

        boutonMenuAjouterDivorce.setText("Ajouter divorce");
        boutonMenuAjouterDivorce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonMenuAjouterDivorceActionPerformed(evt);
            }
        });
        boutonMenuModifierVIP.add(boutonMenuAjouterDivorce);

        boutonMenuAjouterPhoto.setText("Ajouter une photo");
        boutonMenuModifierVIP.add(boutonMenuAjouterPhoto);

        jMenuBar1.add(boutonMenuModifierVIP);

        jMenu2.setText("A propos");

        boutonMenuAide.setText("Aide");
        jMenu2.add(boutonMenuAide);

        boutonMenuAPropos.setText("A propos de voicela");
        boutonMenuAPropos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonMenuAProposActionPerformed(evt);
            }
        });
        jMenu2.add(boutonMenuAPropos);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boutonMenuModifierMariageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonMenuModifierMariageActionPerformed
        AjouterMariage BddAjouterMariage;
        BddAjouterMariage = new AjouterMariage(this, true);
        BddAjouterMariage.setLocation(250, 150);
        BddAjouterMariage.setVisible(true);
    }//GEN-LAST:event_boutonMenuModifierMariageActionPerformed

    private void boutonMenuAjouterDivorceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonMenuAjouterDivorceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonMenuAjouterDivorceActionPerformed

    private void boutonMenuAProposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonMenuAProposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonMenuAProposActionPerformed

    private void ajoutVIP(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutVIP
        AjoutVip BddVip;
        BddVip = new AjoutVip(this, true);
        BddVip.setLocation(250, 150);
        BddVip.setVisible(true);

    }//GEN-LAST:event_ajoutVIP

    private void boutonMenuModifierVIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonMenuModifierVIPActionPerformed
        
    }//GEN-LAST:event_boutonMenuModifierVIPActionPerformed

    public ArrayList<VIP> lireLesVIP() throws Exception {
        // Affichage de tous les vip
        PreparedStatement pstmt = null;
        Connection connection = null;
        ResultSet rs = null;
        
        try {
            Connexion cnx = new Connexion();
            connection = cnx.Connecter();
            String requete = "SELECT * FROM vip";
            pstmt = connection.prepareStatement(requete);
            rs = pstmt.executeQuery(); // Exécuter la requête
            
            while (rs.next()) {
                VIP v;
                v = new VIP();
                
                String nom = rs.getString(2); // nom
                String prenomUsage = rs.getString(3); // prenom usage
                String prenom = rs.getString(4); // prenom
                String sexe = rs.getString(12);// sexe 
                String civilite = rs.getString(6); // civilité
                int age = rs.getInt(8);    // age
                String statut = rs.getString(10);// statut
                String lieuNaissance = rs.getString(9); // lieu de naissance
                String dateNaissance = rs.getString(7); // date de naissance
                int nbEnfants = rs.getInt(11);   // nombre d'enfants
                String nationalite = rs.getString(5); // nationalité
                
                v.setNom(nom);
                v.setPrenomUsage(prenomUsage);
                v.setPrenoms(prenom);
                v.setSexe(sexe);
                v.setCivilité(civilite);
                v.setAge(age);
                v.setStatut(statut);
                v.setLieuNaissance(lieuNaissance);
                v.setDateNaissance(dateNaissance);
                v.setEnfants(nbEnfants);
                v.setNationalite(nationalite);
                vVIP.add(v);
                pstmt.close();
            }
        } catch (Exception e) {
            throw e;
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (pstmt != null) {
                    pstmt.close();
                }
                if (connection != null) {
                    connection.close();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
        return vVIP;
    }
    // Connexion
    //public static java.sql.Connection conn;

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Appli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Appli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Appli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Appli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        new Admin().setVisible(true);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new Appli().setVisible(false);
                } catch (Exception ex) {
                    Logger.getLogger(Appli.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem boutonMenuAPropos;
    private javax.swing.JMenuItem boutonMenuAide;
    private javax.swing.JMenuItem boutonMenuAjouterDivorce;
    private javax.swing.JMenuItem boutonMenuAjouterPhoto;
    private javax.swing.JMenuItem boutonMenuAjouterVIP;
    private javax.swing.JMenuItem boutonMenuModifierMariage;
    private javax.swing.JMenu boutonMenuModifierVIP;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
    private final MonModele monModele;
    private final java.util.ArrayList<VIP> vVIP;
}
